### ISSUE TITLE
`tx push -t` doesn't work

### ISSUE THREAD

**Issue by eight04** [transifex/cli#20] opened 2022-02-16 21:41 UTC
```
C:\Users\eight04\dev\image-picka>tx push -t -f

# Resource o:image-picka:p:image-picka:r:messagesjson

 SUCCESS  Organization 'image-picka' fetched
 SUCCESS  Project 'image-picka' fetched
 SUCCESS  Resource with slug 'messagesjson' found
 SUCCESS  Stats fetched

Pushing translations:

 SUCCESS  Project's remote languages fetched: zh_CN, zh_TW, es_419, fr, nl, nl_NL, ru_RU, tr
```
`tx` exits immediately after printing the last line. I don't see any error.

Repo: https://github.com/eight04/image-picka
Transifex project: https://www.transifex.com/image-picka/image-picka/dashboard/
TX Client, version=1.0.0

**Comment by codegaze** [comment] 2022-02-17 14:35
Hey @eight04, thanks for reaching out and for providing the data to reproduce this! :) 

As far as I can understand this happens because we use the operating's system path separator (`\` in Windows) to split the `file_filter` path and in this case the `file_filter` the path has `/` in it which will result to not finding the files.

We need to rethink the way we do this and provide better messaging, but in order to unblock your workflow for now I would suggest, if you are pushing from your local machine, to make the following change to your `config` file without pushing it to your repo, since `pull` happens in a linux machine.

```
file_filter = src/static/_locales/<lang>/messages.json
```
to 
```
file_filter = src\static\_locales\<lang>\messages.json
```

**Comment by codegaze** [comment] 2022-02-18 08:06
I'm glad to hear it @eight04. I will leave this issue open until we have an update! Cheers.

**Comment by codegaze** [comment] 2022-02-23 11:14
Hey @eight04, we just release a new version (`v1.0.2`) that should tackle this issue. Please feel free to test it and close this one.

**Comment by codegaze** [comment] 2022-02-28 07:23
Yes, let's close this one. I believe the `503` was a random thing and it shouldn't be a problem :)

**Closed by codegaze** 2022-02-28 07:23 UTC
Labels: bug
